/* used to generate the random words for the game.  I've read this can be done a number of dynamic ways
that I'm sure will be touched upon on future topics */
const randomWords = [
  "javascript",
  "typescript",
  "python",
  "ruby",
  "java",
  "php",
  "html",
  "css",
  "sass",
  "react",
  "angular",
  "vue",
  "node",
  "express",
  "django",
  "flask",
  "frontend",
  "backend",
  "fullstack",
  "graphql",
  "restapi",
  "webpack",
  "babel",
  "eslint",
  "tailwind",
  "bootstrap",
  "git",
  "github",
  "npm",
  "vscode",
  "terminal",
  "debugging",
  "testing",
  "deployment",
  "hosting",
  "seo",
  "cookies",
  "session",
  "authentication",
  "database",
  "server",
  "client",
  "response",
  "request",
  "protocol",
  "domain",
  "routing",
  "rendering",
  "responsive",
  "cache",
  "cdn",
  "middleware"
];

export default randomWords;